//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkWindowsApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SidewalkContext : DbContext
    {
        public SidewalkContext()
            : base("name=SidewalkContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AffidavitCosts> AffidavitCosts { get; set; }
        public virtual DbSet<AffidavitCostsDetail> AffidavitCostsDetail { get; set; }
        public virtual DbSet<AffidavitCostsDetailObject> AffidavitCostsDetailObject { get; set; }
        public virtual DbSet<AffidavitNote> AffidavitNote { get; set; }
        public virtual DbSet<CityContract> CityContract { get; set; }
        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<CostType> CostType { get; set; }
        public virtual DbSet<Inspector> Inspector { get; set; }
        public virtual DbSet<PermitFee> PermitFee { get; set; }
        public virtual DbSet<PermitFeeRate> PermitFeeRate { get; set; }
        public virtual DbSet<PrintCode> PrintCode { get; set; }
        public virtual DbSet<RepairItem> RepairItem { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sw_action> sw_action { get; set; }
        public virtual DbSet<sw_action_detail> sw_action_detail { get; set; }
        public virtual DbSet<sw_posting> sw_posting { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasure { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<Affidavit> Affidavit { get; set; }
        public virtual DbSet<AffidavitDocumentHistory> AffidavitDocumentHistory { get; set; }
    }
}
