//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkPermitWPF.Model
{
    using System;
    
    public partial class getAffidavitCostDetails_Result
    {
        public Nullable<int> aff_no { get; set; }
        public string action { get; set; }
        public string action_type { get; set; }
        public Nullable<double> unit { get; set; }
        public Nullable<decimal> cost { get; set; }
    }
}
