//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffidavitCostsDetail
    {
        public string Affidavit_Key { get; set; }
        public string CostType_Key { get; set; }
        public Nullable<int> RepairItem_Key { get; set; }
        public Nullable<double> Unit { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual CostType CostType { get; set; }
        public virtual RepairItem RepairItem { get; set; }
    }
}
