//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspector
    {
        public Inspector()
        {
            this.Affidavit = new HashSet<Affidavit>();
        }
    
        public int InspectorID { get; set; }
        public Nullable<int> Staff_Key { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Affidavit> Affidavit { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
