//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_posting
    {
        public int aff_no { get; set; }
        public string qtr_sec { get; set; }
        public string map_id { get; set; }
        public Nullable<System.DateTime> post_dt { get; set; }
        public Nullable<int> acct_period { get; set; }
        public string property_id { get; set; }
        public string property_id2 { get; set; }
        public string property_desc { get; set; }
        public Nullable<int> aff_status { get; set; }
        public string owner_name { get; set; }
        public string attn1 { get; set; }
        public string attn2 { get; set; }
        public string st_no { get; set; }
        public string district { get; set; }
        public string st_name { get; set; }
        public string designator { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public Nullable<int> inspector_no { get; set; }
        public string city_owned_flag { get; set; }
        public string owner_resident_flag { get; set; }
        public string service_req_flag { get; set; }
        public string rep_by_city { get; set; }
        public string rep_by_owner { get; set; }
        public string partial_repair { get; set; }
        public string vacant_lot_flag { get; set; }
        public string vacant_desc { get; set; }
        public Nullable<System.DateTime> repair_dt { get; set; }
        public Nullable<System.DateTime> billed_dt { get; set; }
        public string bill_flag { get; set; }
        public Nullable<System.DateTime> hold_until_dt { get; set; }
        public Nullable<int> permit_no { get; set; }
        public string permit_issued { get; set; }
        public string permit_extended { get; set; }
        public Nullable<System.DateTime> date_issued { get; set; }
        public Nullable<System.DateTime> date_expired { get; set; }
        public string contractor { get; set; }
        public string builder_board_no { get; set; }
        public string license_no { get; set; }
        public Nullable<System.DateTime> date_cancelled { get; set; }
        public string cancelled_by { get; set; }
        public string status { get; set; }
        public string last_action { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> sent_dt { get; set; }
        public string NEW_AFF { get; set; }
        public bool NEW_ClearWalk { get; set; }
        public Nullable<System.DateTime> NEW_RepairDueDate { get; set; }
        public string inspector_name { get; set; }
        public string fname { get; set; }
    }
}
