//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_action
    {
        public int aff_no { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> action_dt { get; set; }
        public Nullable<System.DateTime> cost_dt { get; set; }
        public Nullable<int> contract_id { get; set; }
        public Nullable<decimal> special_cost { get; set; }
        public Nullable<decimal> move_in { get; set; }
        public Nullable<decimal> adjustment { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public string comments { get; set; }
        public string @override { get; set; }
        public string fis_name { get; set; }
        public string batch_id { get; set; }
    }
}
