//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitPayment
    {
        public long PermitPaymentID { get; set; }
        public Nullable<long> PermitID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuedBy { get; set; }
        public string PaymentMethod { get; set; }
        public string ApprovalCode { get; set; }
        public string CheckNumber { get; set; }
        public string Notes { get; set; }
    
        public virtual Permit Permit { get; set; }
    }
}
