//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkPermitWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitHistory
    {
        public long PermitHistoryID { get; set; }
        public Nullable<long> PermitID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ActivityTime { get; set; }
        public string Comments { get; set; }
    
        public virtual Permit Permit { get; set; }
    }
}
