//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkWindowsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public UnitOfMeasure()
        {
            this.RepairItem = new HashSet<RepairItem>();
        }
    
        public System.Guid UomID { get; set; }
    
        public virtual ICollection<RepairItem> RepairItem { get; set; }
    }
}
