//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffidavitCosts
    {
        public string Affidavit_Key { get; set; }
        public string CostType_Key { get; set; }
        public Nullable<System.DateTime> ActionDt { get; set; }
        public Nullable<int> Contract_Key { get; set; }
        public Nullable<decimal> Parking { get; set; }
        public Nullable<decimal> MoveIn { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string Comments { get; set; }
        public string VisioDiagram { get; set; }
        public string Batch_Key { get; set; }
    
        public virtual CostType CostType { get; set; }
    }
}
