//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_action_detail
    {
        public int aff_no { get; set; }
        public string action { get; set; }
        public string action_type { get; set; }
        public Nullable<double> unit { get; set; }
        public Nullable<decimal> cost { get; set; }
    }
}
