//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkWindowsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public Contractor()
        {
            this.CityContract = new HashSet<CityContract>();
        }
    
        public int ContractorID { get; set; }
        public string ContractorName { get; set; }
        public string CCB { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public Nullable<byte> MBE { get; set; }
        public Nullable<byte> WBE { get; set; }
        public Nullable<byte> ESB { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<byte> CityContractor { get; set; }
    
        public virtual ICollection<CityContract> CityContract { get; set; }
    }
}
