//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.AffidavitDocumentHistory = new HashSet<AffidavitDocumentHistory>();
            this.Inspector1 = new HashSet<Inspector>();
        }
    
        public int PERNR { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Supervisor { get; set; }
        public Nullable<bool> Inspector { get; set; }
        public Nullable<bool> Forms { get; set; }
        public Nullable<bool> Final { get; set; }
        public Nullable<bool> Permit { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<AffidavitDocumentHistory> AffidavitDocumentHistory { get; set; }
        public virtual ICollection<Inspector> Inspector1 { get; set; }
    }
}
