//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkPermitWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSESSOR
    {
        public string RNUM { get; set; }
        public string STATE_ID { get; set; }
        public string NEW_STATE_ID { get; set; }
        public string PROPERTY_ID { get; set; }
        public string OWNER1 { get; set; }
        public string OWNER2 { get; set; }
        public string OWNER3 { get; set; }
        public string OWNER_ADDRESS { get; set; }
        public string OWNER_CITY { get; set; }
        public string OWNER_STATE { get; set; }
        public string OWNER_ZIP { get; set; }
        public string SITE_ADDRESS_NUMBER { get; set; }
        public string SITE_STREET_DIRECTION { get; set; }
        public string SITE_STREET_NAME { get; set; }
        public string SITE_STREET_TYPE { get; set; }
        public string SITE_UNIT_TYPE { get; set; }
        public string SITE_UNIT_NUMBER { get; set; }
        public string SITE_ADDRESS_FULL { get; set; }
        public string SITE_CITY { get; set; }
        public string SITE_STATE { get; set; }
        public string SITE_ZIP { get; set; }
        public string SITE_CITY_STATE_ZIP { get; set; }
        public string INSTRUMENT_NUMBER { get; set; }
        public string MAP_NUMBER { get; set; }
        public string LEGAL_DESCRIPTION { get; set; }
        public string LOT { get; set; }
        public string BLOCK { get; set; }
        public string TAXCODE { get; set; }
        public Nullable<int> PARCEL_SQUARE_FEET { get; set; }
        public Nullable<int> PARCEL_WIDTH_FOOTAGE { get; set; }
        public Nullable<short> PARCEL_LENGTH_FOOTAGE { get; set; }
        public string PROPERTY_CODE { get; set; }
        public string PROPERTY_CODE_DESC { get; set; }
        public string LANDUSE { get; set; }
        public string YEAR_BUILT { get; set; }
        public Nullable<int> BLDGSQFT { get; set; }
        public Nullable<int> NUMBER_OF_BEDROOMS { get; set; }
        public Nullable<int> NUMBER_OF_STORIES { get; set; }
        public Nullable<int> NUMBER_OF_UNITS { get; set; }
        public string MARKET_VALUE_YEAR1 { get; set; }
        public Nullable<int> MARKET_VALUE_LAND1 { get; set; }
        public Nullable<int> MARKET_VALUE_IMPROVEMENTS1 { get; set; }
        public Nullable<int> MARKET_VALUE_TOTAL1 { get; set; }
        public Nullable<int> MARKET_EXEMPTION_VALUE1 { get; set; }
        public Nullable<int> M50_ASSESSED_VALUE1 { get; set; }
        public string ASSESSED_VALUE_YEAR1 { get; set; }
        public Nullable<int> ASSESSED_VALUE1 { get; set; }
        public string MARKET_VALUE_YEAR2 { get; set; }
        public Nullable<int> MARKET_VALUE_LAND2 { get; set; }
        public Nullable<int> MARKET_VALUE_IMPROVEMENTS2 { get; set; }
        public Nullable<int> MARKET_VALUE_TOTAL2 { get; set; }
        public Nullable<int> MARKET_EXEMPTION_VALUE2 { get; set; }
        public Nullable<int> M50_ASSESSED_VALUE2 { get; set; }
        public string ASSESSED_VALUE_YEAR2 { get; set; }
        public Nullable<int> ASSESSED_VALUE2 { get; set; }
        public string MARKET_VALUE_YEAR3 { get; set; }
        public Nullable<int> MARKET_VALUE_LAND3 { get; set; }
        public Nullable<int> MARKET_VALUE_IMPROVEMENTS3 { get; set; }
        public Nullable<int> MARKET_VALUE_TOTAL3 { get; set; }
        public Nullable<int> MARKET_EXEMPTION_VALUE3 { get; set; }
        public Nullable<int> M50_ASSESSED_VALUE3 { get; set; }
        public string ASSESSED_VALUE_YEAR3 { get; set; }
        public Nullable<int> ASSESSED_VALUE3 { get; set; }
        public string SALEDATE { get; set; }
        public Nullable<int> SALEPRICE { get; set; }
        public string EXEMPTION_VALUE_YEAR1 { get; set; }
        public Nullable<decimal> EXEMPTION_VALUE_LAND1 { get; set; }
        public Nullable<decimal> EXEMPTION_VALUE_IMPROVEMENTS1 { get; set; }
        public string EXEMPTION_VALUE_YEAR2 { get; set; }
        public Nullable<decimal> EXEMPTION_VALUE_LAND2 { get; set; }
        public Nullable<decimal> EXEMPTION_VALUE_IMPROVEMENTS2 { get; set; }
        public string EXEMPTION_VALUE_YEAR3 { get; set; }
        public Nullable<decimal> EXEMPTION_VALUE_LAND3 { get; set; }
        public Nullable<decimal> EXEMPTION_VALUE_IMPROVEMENTS3 { get; set; }
        public string COUNTY { get; set; }
        public string ACCOUNT_STATUS_CODE { get; set; }
        public string RATIO_CODE { get; set; }
        public Nullable<byte> IS_CONDO { get; set; }
        public string PARENT_ID { get; set; }
        public Nullable<byte> IS_FAKE_PARENT { get; set; }
        public Nullable<int> SAME_OWNER_SITE_ADDR { get; set; }
        public Nullable<int> X_COORD { get; set; }
        public Nullable<int> Y_COORD { get; set; }
    }
}
