//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffidavitDocumentHistory
    {
        public long ID { get; set; }
        public string Affidavit_Key { get; set; }
        public string DocType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocStatus { get; set; }
        public Nullable<int> DocBy { get; set; }
    
        public virtual Affidavit Affidavit { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
