//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffidavitFormInspection
    {
        public long FormInspectionId { get; set; }
        public long AffidavitId { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public bool Sidewalk { get; set; }
        public bool Driveway { get; set; }
        public bool Curb { get; set; }
        public bool Partial { get; set; }
        public string PartialDescription { get; set; }
        public bool MatchJointPattern { get; set; }
        public bool PlaceJoints { get; set; }
        public bool ToolDeepJoints { get; set; }
        public string OtherGrantedToPour { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public bool PermissionGranted { get; set; }
        public bool NotReady { get; set; }
        public bool InsufficientBarricades { get; set; }
        public bool RemoveDebris { get; set; }
        public bool NotDeep { get; set; }
        public bool CurbHeight { get; set; }
        public bool SawCutEdges { get; set; }
        public bool NoPermit { get; set; }
        public bool AddCrushedRock { get; set; }
        public string OtherDoNotPour { get; set; }
        public Nullable<System.DateTime> FormFailDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> FormFailInspectorId { get; set; }
        public Nullable<int> FormPassInspectorId { get; set; }
    
        public virtual Affidavit Affidavit { get; set; }
        public virtual Inspector Inspector { get; set; }
        public virtual Inspector Inspector1 { get; set; }
    }
}
