//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffidavitFinalInspection
    {
        public long FinalInspectionId { get; set; }
        public long AffidavitID { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public bool Sidewalk { get; set; }
        public bool Driveway { get; set; }
        public bool Curb { get; set; }
        public bool ContractorRepaired { get; set; }
        public bool ContractorRepairedNotCitySpec { get; set; }
        public bool OwnerRepaired { get; set; }
        public bool OwnerRepairedNotCitySpec { get; set; }
        public string OtherRepairsAreCompleteAndSatisfactory { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public bool RepairsComplete { get; set; }
        public bool RemoveFormsToGrade { get; set; }
        public bool MoreBackfill { get; set; }
        public bool IncompleteRepairs { get; set; }
        public bool MoreGrinding { get; set; }
        public bool RemoveMarkedAreas { get; set; }
        public bool AsphaltWork { get; set; }
        public bool Graffiti { get; set; }
        public bool NoRightWayPermit { get; set; }
        public string OtherRepairsNotAcceptable { get; set; }
        public Nullable<System.DateTime> FinalFailDate { get; set; }
        public Nullable<int> FinalFailInspectorId { get; set; }
        public Nullable<int> FinalPassInspectorId { get; set; }
    
        public virtual Affidavit Affidavit { get; set; }
        public virtual Inspector Inspector { get; set; }
        public virtual Inspector Inspector1 { get; set; }
    }
}
