//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORT_TAXLOTS_PDX
    {
        public int OBJECTID { get; set; }
        public Nullable<decimal> AREA { get; set; }
        public string STATE_ID { get; set; }
        public string RNO { get; set; }
        public string OWNER1 { get; set; }
        public string OWNER2 { get; set; }
        public string OWNER3 { get; set; }
        public string OWNERADDR { get; set; }
        public string OWNERCITY { get; set; }
        public string OWNERSTATE { get; set; }
        public string OWNERZIP { get; set; }
        public string SITEADDR { get; set; }
        public string SITECITY { get; set; }
        public string SITE_STATE { get; set; }
        public string SITEZIP { get; set; }
        public string LEGAL_DESC { get; set; }
        public string TAXCODE { get; set; }
        public string PROP_CODE { get; set; }
        public string PRPCD_DESC { get; set; }
        public string LANDUSE { get; set; }
        public string YEARBUILT { get; set; }
        public Nullable<decimal> BLDGSQFT { get; set; }
        public Nullable<decimal> BEDROOMS { get; set; }
        public Nullable<decimal> FLOORS { get; set; }
        public Nullable<decimal> UNITS { get; set; }
        public string MKTVALYR1 { get; set; }
        public Nullable<decimal> LANDVAL1 { get; set; }
        public Nullable<decimal> BLDGVAL1 { get; set; }
        public Nullable<decimal> TOTALVAL1 { get; set; }
        public string MKTVALYR2 { get; set; }
        public Nullable<decimal> LANDVAL2 { get; set; }
        public Nullable<decimal> BLDGVAL2 { get; set; }
        public Nullable<decimal> TOTALVAL2 { get; set; }
        public string MKTVALYR3 { get; set; }
        public Nullable<decimal> LANDVAL3 { get; set; }
        public Nullable<decimal> BLDGVAL3 { get; set; }
        public Nullable<decimal> TOTALVAL3 { get; set; }
        public string SALEDATE { get; set; }
        public Nullable<decimal> SALEPRICE { get; set; }
        public string ACC_STATUS { get; set; }
        public Nullable<decimal> A_T_SQFT { get; set; }
        public Nullable<decimal> A_T_ACRES { get; set; }
        public Nullable<decimal> FRONTAGE { get; set; }
        public string COUNTY { get; set; }
        public string SOURCE { get; set; }
        public string PROPERTYID { get; set; }
        public string TLID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
