//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class qip
    {
        public int OBJECTID { get; set; }
        public Nullable<decimal> AREA { get; set; }
        public Nullable<decimal> PERIMETER { get; set; }
        public Nullable<decimal> QTRSEC_ { get; set; }
        public Nullable<decimal> QTRSEC_ID { get; set; }
        public string QTRNO { get; set; }
        public string QTRSEC { get; set; }
        public string SHIFT { get; set; }
        public string FULLSEC { get; set; }
        public string EZONE { get; set; }
        public string FOURSEC { get; set; }
        public Nullable<short> QTRNUM { get; set; }
        public string TOWN { get; set; }
        public string SECT { get; set; }
        public Nullable<int> Shape { get; set; }
    }
}
