//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkPermitWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitFeeRate
    {
        public long PermitFeeID { get; set; }
        public string Action_Type { get; set; }
        public Nullable<decimal> CurrentRate { get; set; }
        public Nullable<decimal> NewEffectiveRate { get; set; }
        public bool Status { get; set; }
    }
}
