//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkWindowsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostType
    {
        public CostType()
        {
            this.AffidavitCosts = new HashSet<AffidavitCosts>();
            this.AffidavitCostsDetail = new HashSet<AffidavitCostsDetail>();
            this.AffidavitCostsDetailObject = new HashSet<AffidavitCostsDetailObject>();
        }
    
        public string CostTypeID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AffidavitCosts> AffidavitCosts { get; set; }
        public virtual ICollection<AffidavitCostsDetail> AffidavitCostsDetail { get; set; }
        public virtual ICollection<AffidavitCostsDetailObject> AffidavitCostsDetailObject { get; set; }
    }
}
