//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidewalkWindowsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepairItem
    {
        public RepairItem()
        {
            this.AffidavitCostsDetail = new HashSet<AffidavitCostsDetail>();
            this.AffidavitCostsDetailObject = new HashSet<AffidavitCostsDetailObject>();
        }
    
        public int RepairItemID { get; set; }
        public string RepairItemType { get; set; }
        public Nullable<System.Guid> UoM_Key { get; set; }
        public string PrintCode_Key { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ShortDescription { get; set; }
    
        public virtual ICollection<AffidavitCostsDetail> AffidavitCostsDetail { get; set; }
        public virtual ICollection<AffidavitCostsDetailObject> AffidavitCostsDetailObject { get; set; }
        public virtual PrintCode PrintCode { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
