//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidewalk.Logic.Database
{
    using System;
    
    public partial class ufnGetPostCostSummary_Result
    {
        public Nullable<int> iYear { get; set; }
        public string sYear { get; set; }
        public Nullable<int> iMonth { get; set; }
        public string sMonth { get; set; }
        public Nullable<int> aff_no { get; set; }
        public string aff_action { get; set; }
        public Nullable<decimal> cost { get; set; }
    }
}
